### ISSUE TITLE
Not ideal model naming convention

### ISSUE THREAD

**Issue by claes-work** [Asset-Rebalancing-Tool/ApiScaffold#2]
"PostOwnedPublicShares" and "PostOwnedPrivateShares" are not ideal naming conventions.
The term "shares" will no longer be used in frontend and shouldn't be used in backend.
The equivalent to "shares" is "ownedQuantity" and "ownedQuantity" does not describe owned assets.

Why don't we use "PostOwnedPublicAssets" & "PostOwnedPrivateAssets" instead?
If you need a differenciation between  those assets that are getting fetched in the search process and those that are already owned by a user, I would suggest to differ it by 

PublicAssets -> Model for assets that are getting fetched
OwnedPublicAssets -> Model for assets that are owned

**Comment by tobi97h** [comment]
Fixxed in https://github.com/Asset-Rebalancing-Tool/ApiScaffold/commit/0424c0f505622a5f238d0d51b7d19ea0a3fe4948 / https://github.com/Asset-Rebalancing-Tool/ApiScaffold/commit/acbd15cbd289473d2f7c2d6649cd7cab7c33212a
