### ISSUE TITLE
Enum assetType Uppercase

### ISSUE THREAD

**Issue by claes-work** [Asset-Rebalancing-Tool/ApiScaffold#3]
The assetType Enum "Etf" value should be uppercase. I can parse it in frontend if you want to, but for consistency I would prefer if the value as always saved in uppercase.

**Comment by tobi97h** [comment]
```
public enum AssetType {
    Stock, Fond, Etf, Commodity, PreciousMetals, Crypto, Other
}
```

Is already uppercase?

**Comment by claes-work** [comment]
Was resolved by mapping the values in Frontend in commit 57aadd9775a492057ea511747857e01094291c9f
