### ISSUE TITLE
[API] [DELETE] DeleteAssetHoldingGroup

### ISSUE THREAD

**Issue by claes-work** [Asset-Rebalancing-Tool/ApiScaffold#7]
Der `DeleteAssetHoldingGroup` Endpunkt müsste bitte auch die zu der Gruppe zugehörigen `Public- & PrivateHoldings` löschen.\
Ich hatte im Frontend beim Löschen der Gruppe jeweils das Löschen der Holdings einzeln angefeuert. Das ist allerdings manchmal etwas buggy.\
Ich vermute es liegt daran, dass ich alle Anfragen auf einmal stelle und das backend nicht damit klar kommt.
Wenn eine Gruppe 20 PublicHoldings hat, wird eine Anfrage für das löschen der Gruppe, sowie 20 Anfragen für jedes einzelne PublicHolding gefeuert.\
Es wäre daher besser, wenn du beim Request für das Löschen einer Gruppe, im Backend alle zugehörigen Holdings löschst

**Comment by tobi97h** [comment]
fixed in 00da6832dbcd0b2a8927fc7a112850a680ed78b0

**Comment by tobi97h** [comment]
pls verify

**Comment by claes-work** [comment]
pls assign back to me, so I get notified by email ;)

**Comment by claes-work** [comment]
Kann ich nicht überprüfen, weil die HoldingGroups broken sind.
Ich bekomme keine Public- & PrivatHoldings zurrück

Inital -> GET /holding_api/asset_holding/group
Keine Public- oder PrivateHoldings verschachtelt:
![grafik](https://user-images.githubusercontent.com/86721650/197550689-96af09d0-0b1b-4c5f-9c70-f6160e7809aa.png)

Holding Group Patch Request gemacht -> PATCH /holding_api/asset_holding/group
![grafik](https://user-images.githubusercontent.com/86721650/197550904-247a34f3-f2b0-4a2e-bedd-0639ad78efab.png)

Holding Group Patch Request Response (sieht gut aus):
![grafik](https://user-images.githubusercontent.com/86721650/197551046-379d5407-3ce0-4710-9cd8-54920e57b1da.png)

Nach Reload -> GET /holding_api/asset_holding/group
Keine Public- oder PrivateHoldings verschachtelt:
![grafik](https://user-images.githubusercontent.com/86721650/197551262-3d42e0ab-144e-4c6e-807a-3c81570e72a1.png)
