### ISSUE TITLE
Delete holding from group

### ISSUE THREAD

**Issue by claes-work** [Asset-Rebalancing-Tool/ApiScaffold#9]
Wenn ein holding in einer Gruppe verschachtelt ist, funktioniert der delete Endpunkt nicht.
Ich bekomme einen 500er Internal Server Error zurrück.
Das Entfernen von holdings außerhalb einer Gruppe und das Auflösen der Gruppe selbst funktioniert wunderbar.

**Comment by tobi97h** [comment]
fixed in 89e35940cb5adf5cc070d785e495004b6ccaaaa4

**Comment by tobi97h** [comment]
fixxed in 89e35940cb5adf5cc070d785e495004b6ccaaaa4
